
import { Navbar } from "./component/navbar";
import {Inter} from "next/font/google"
import "./globals.css";
import Footer from "./component/footer";

const inter = Inter({ subsets: ["latin"]});
export const Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
    children: React.ReactNode;
    }) {
      return (
        <html lang="en">
          <body className={inter.className}>
            <Navbar/>
            {children}
            <Footer/>
          </body>
        </html>
      );
    }

